name: testing
on:
  workflow_dispatch:
    inputs:
      foo:
        description: good testing
jobs:
  yell:
    runs-on: ubuntu-latest
    steps:
      - name: listrunningworkflows
        run: |
          yes | gh auth login -w
      - name: complete
        run: |
          ls
